title: "Mickaël Dardaillon"
description: "Mickaël Dardaillon home page"
url: "https://dardarel.github.io"

theme: minima

email: "mickael.dardaillon@insa-rennes.fr"
github_username: dardarel
flickr_username: dardarel
linkedin_username: mickaeldardaillon

header_pages:
  - publications/index.md
  - teaching/index.md
  - tutorials/index.md
  - events/index.md
